module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    CATEGORY_COLLECTION:'category',
    WISHLIST_COLLECTION:'wishlist',
    OFFER_COLLECTION:'offer',
}